### ISSUE TITLE
Enable `smart contracts` when initialized as rollapp

### ISSUE THREAD

**Issue by mtsitrin** [dymensionxyz/ethermint#8]
For the hub, we enforced that smart contracts can't be created and can't be changed by gov.

It's too strict, as we want to reuse this repo for the rollapps

We need to have a feature flag for that enforcement, that will be set differently in the `app.go` of hub/rollapp

**Comment by omritoptix** [comment]
@mtsitrin this is connected to the VFC PR. is it by mistake or is the flag is also there?

**Comment by mtsitrin** [comment]
VFC have different implementation but it handles it. The VFC PR will close this issue
